# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7286a0e71d247781004dcb1aed11cea75d84ff10e6b39b84020c876a31e9775a61122be8c330971a553988384bdc1a2850ab986886c0ef17712997133d81b9fd

test:
  secret_key_base: 483741f2f3559729f6dcefaace54ec62896691ea500502dc107f0c43ec98654106d843cf81ae67ede5f4d91c118fd4be9048ebad0fc3658f4940cd6a0a790711

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
